[package]
name = "phoenix"
version = "0.1.0"
authors = ["Nick Coish <nick.coish@gmail.com>"]

[lib]
name = "phoenix"
path = "src/lib.rs"

[[bin]]
name = "test_binary"
path = "src/bin.rs"

[dependencies]
websocket = "~>0.20"
